#index:
#    path: /
#    controller: App\Controller\DefaultController::index

widget_administration:
    prefix: /admin
    resource: "../bundle/WidgetBundle/Resources/config/routes.yaml"

sso_auth:
    path: /authenticate/sso

authenticate:
    path: /authenticate
    defaults:
        _controller: App\Controller\AuthenticateAction

logout:
    path: /authenticate/logout

admin_dashboard:
    path: /admin
    defaults:
        _controller: App\Controller\Admin\View\DashboardAction

admin_context_change:
    path: /admin/context/change/{contextId}
    defaults:
        _controller: App\Controller\Admin\ContextChangeAction
    requirements:
        contextId: \d+
        return: http[s]?\:\/\/[a-z0-9\-\.\/]+
